#ifndef __DHT11_H
#define __DHT11_H

#include "main.h" // Includes HAL types and your main MCU configuration
#include "tim.h"  // For your timer handle (e.g., htim2)

// Define the GPIO port and pin connected to DHT11 Data line
#define DHT11_PORT      GPIOB   // Change to your chosen port (e.g., GPIOB, GPIOC)
#define DHT11_PIN       GPIO_PIN_5 // Change to your chosen pin (e.g., GPIO_PIN_5, GPIO_PIN_1)

// Define the Timer Handle used for microsecond delays
// Replace htim2 with the actual name of your timer handle generated by CubeMX (e.g., htim3, htim4)
extern TIM_HandleTypeDef htim2;


// Function Prototypes
void DHT11_Init(void);
uint8_t DHT11_Read_Data(float *temperature, float *humidity, uint8_t raw_data[5]);

#endif /* __DHT11_H */
